version: '3.8'

services:
  multi-agent-system:
    build: .
    container_name: multi-agent-system
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    command: streamlit run app.py
